# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        '/:title'

# Setup
title:            Nathan Reid
tagline:          'Life, Software, and the Pursuit of Everything'
description:      'A blog about architecting solutions, developing software, and building dreams.'
url:              http://nathantreid.com
staging_url:      http://staging.nathantreid.com
baseurl:          '/'
paginate:         10

author:
  name:           'Nathan Reid'
  url:            https://twitter.com/nathantreid

# Custom vars
version:          1.0.0

pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

disqus:
  shortname: 'nathantreid'
  staging_shortname: 'nathantreid-staging'

staging: true

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'default'
      comments: true

